version: '3.5'

volumes:
  postgres_data:
  nginx_config:
  static_content:

services:

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: dartamid/dart_foodgram:latest
    restart: always
    volumes:
      - nginx_config:/code/nginx
      - static_content:/code/staticfiles
    depends_on:
      - db

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - static_content:/static
    ports:
      - 80:80
    depends_on:
      - web