# Generated by Django 2.2.6 on 2021-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='в минутах', verbose_name='Время приготовления'),
        ),
    ]
